services:
  # Database MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=iqplus_db
    networks:
      - etl_network

  # PostgreSQL for Airflow
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - etl_network

  # Chrome for Selenium
  chrome:
    image: selenium/standalone-chrome:123.0
    container_name: selenium-chrome
    shm_size: 2gb
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_SESSION_TIMEOUT=60
    networks:
      - etl_network
  # Extraction Service
  extraction-iqplus:
    build:
      context: ./services/extraction
      dockerfile: Dockerfile
    container_name: extraction-iqplus
    ports:
      - "5000:5000"
    volumes:
      - shared_data:/app/data
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - CHROME_URL=http://chrome:4444/wd/hub
    depends_on:
      - mongodb
      - chrome
    networks:
      - etl_network
  # Transform Service with LLM
  transform-llm:
    build:
      context: ./services/transform
      dockerfile: Dockerfile
    container_name: transform-llm
    ports:
      - "5001:5001"
    volumes:
      - shared_data:/app/data
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - TOGETHER_API_KEY=4c5b75b56495e70bfbc07e2bb033a0f752585d0797fa366fffb0d2626a51911b
    depends_on:
      - mongodb
    networks:
      - etl_network

  # Load Service
  load-service:
    build:
      context: ./services/load
      dockerfile: Dockerfile
    container_name: load-service
    ports:
      - "5002:5002"
    volumes:
      - shared_data:/app/data
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - etl_network

  # Airflow Webserver
  airflow-webserver:
    build:
      context: ./services/airflow
      dockerfile: Dockerfile
    container_name: airflow-webserver
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - EXTRACTION_SERVICE_URL=http://extraction-iqplus:5000
      - TRANSFORM_SERVICE_URL=http://transform-llm:5001
      - LOAD_SERVICE_URL=http://load-service:5002
    volumes:
      - ./services/airflow/dags:/opt/airflow/dags
      - airflow_data:/opt/airflow
      - shared_data:/opt/airflow/shared
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8081:8080"
    entrypoint: /bin/bash
    command: -c "airflow db init && airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin && exec airflow webserver"
    depends_on:
      - postgres
      - extraction-iqplus
      - transform-llm
      - load-service
    networks:
      - etl_network

  # Airflow Scheduler
  airflow-scheduler:
    build:
      context: ./services/airflow
      dockerfile: Dockerfile
    container_name: airflow-scheduler
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - EXTRACTION_SERVICE_URL=http://extraction-iqplus:5000
      - TRANSFORM_SERVICE_URL=http://transform-llm:5001
      - LOAD_SERVICE_URL=http://load-service:5002
    volumes:
      - ./services/airflow/dags:/opt/airflow/dags
      - airflow_data:/opt/airflow
      - shared_data:/opt/airflow/shared
      - /var/run/docker.sock:/var/run/docker.sock
    command: airflow scheduler
    depends_on:
      - airflow-webserver
      - postgres
    networks:
      - etl_network

networks:
  etl_network:
    name: etl_iqplus_financial_net

volumes:
  postgres_data:
  airflow_data:
  mongodb_data:
  shared_data:
